import {
  LayoutDashboard,
  Package,
  ShoppingCart,
  FileText,
  Receipt,
  BarChart3,
  Truck,
  Bot,
  Settings,
  HelpCircle,
  LogOut,
  Search,
  Bell,
  Package2,
  AlertTriangle,
  TrendingUp,
  TrendingDown,
  Plus,
  Pencil,
  Trash2,
  X,
  Minus,
  Banknote,
  CreditCard,
  Smartphone,
  Calendar,
  DollarSign,
  Store,
  Mail,
  Phone,
  CalendarDays,
  CheckCircle,
  Lightbulb,
  BarChart,
  LineChart,
  PieChart,
  ChevronLeft,
  ChevronRight,
  RefreshCw,
  Send,
} from 'lucide-react';

export const Icon = {
  Dashboard: LayoutDashboard,
  Package: Package,
  ShoppingCart: ShoppingCart,
  FileText: FileText,
  Receipt: Receipt,
  BarChart: BarChart3,
  Truck: Truck,
  Bot: Bot,
  Settings: Settings,
  Help: HelpCircle,
  Logout: LogOut,
  Search: Search,
  Notifications: Bell,
  POS: RefreshCw,
  Inventory: Package2,
  Warning: AlertTriangle,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  Add: Plus,
  Edit: Pencil,
  Delete: Trash2,
  Close: X,
  Plus: Plus,
  Minus: Minus,
  Payments: Banknote,
  CreditCard: CreditCard,
  Smartphone: Smartphone,
  Calendar: Calendar,
  Money: DollarSign,
  Supplier: Truck,
  Store: Store,
  Email: Mail,
  Phone: Phone,
  CalendarMonth: CalendarDays,
  CheckCircle: CheckCircle,
  ReceiptLong: Receipt,
  Lightbulb: Lightbulb,
  BarChart2: BarChart,
  LineChart: LineChart,
  PieChart: PieChart,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Send: Send,
};

export default Icon;
